---
- name: Configure PostgreSQL Master for Replication
  hosts: master
  become: yes
  vars:
    replication_user: "replication_user"
    replication_password: "password12345"
  tasks:

    - name: Configure PostgreSQL to listen on specific addresses
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        line: "listen_addresses = '{{ master_address }}, 127.0.0.1'"
        state: present

    - name: Restart PostgreSQL
      service:
        name: postgresql@16-main.service
        state: restarted

    - name: Ensure python3-pip is installed (Debian-based)
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install psycopg2 Python package for PostgreSQL (Debian-based)
      apt: 
        name: python3-psycopg2
        state: present
        update_cache: yes

    - name: Ensure pipelining is enabled
      ansible.builtin.set_fact:
        ansible_pipelining: True

    - name: Create replication user
      become: true
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ replication_user }}"
        password: "{{ replication_password }}"
        encrypted: yes
        state: present

    - name: Grant replication privileges to replication_user
      become: yes
      become_user: postgres
      shell: psql -c "ALTER USER {{ replication_user }} WITH REPLICATION;"

    - name: Configure pg_hba.conf for replication user
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        line: "host {{ item.database }} {{ replication_user }} {{ hostvars[item.slave].slave_address }}/32 md5"
        state: present
      loop:
        - { database: "all", slave: "{{ groups['slave'] | first }}" }
        - { database: "replication", slave: "{{ groups['slave'] | first }}" }
      loop_control:
        loop_var: item

    - name: Reload PostgreSQL
      service:
        name: postgresql@16-main.service
        state: reloaded